FROM alpine:3

# Metadata
LABEL author="Muhammad Dwi Susanto"
LABEL company="Sugiono Family" website="https://mdwisu.github.io/"

RUN mkdir hello
RUN echo "Hello World" > hello/hello.txt

CMD cat hello/hello.txt